---
# tasks file for nginx-role
- name: Add EPEL repository
  yum:
    name: epel-release
    state: present
- name: install nginx
  yum:
    name: nginx
    state: present
  tags: [nginx]

- name: copy nginx configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: restart nginx
  tags: [nginx, config]

- name: Service NGINX restart and enable on boot
  systemd:
    name: nginx
    state: restarted
    enabled: yes
    daemon_reload: yes
 
