---
- name: Datadog-agent
  hosts: nginxserver
  become: yes
  roles:
    - datadog.datadog
  vars:
    datadog_api_key: "some_api_key"
    datadog_site: "datadoghq.com"

- name: Tomcat-server
  hosts: myserver
  become: yes
  roles:
   - tomcat-role

- name: Nginx-server
  hosts: nginxserver
  become: yes
  roles:
    - nginx-role

#- name: Nexus
#  hosts: nexus
#  become: yes
#  roles:
#    - nexus-role
